site_name: CivicTechJobs Docs
site_url: https://hackforla.github.io/CivicTechJobs/

# Optionals
edit_uri: ""
nav:
  - Joining the Team:
      - Intro: joining-the-team/intro.md
      - Content Writer: joining-the-team/content-writer.md
      - Data Scientist: joining-the-team/data-scientist.md
      - Project Manager: joining-the-team/product-manager.md
      - UI/UX Designer: joining-the-team/uiux-designer.md
      - UI/UX Researcher: joining-the-team/uiux-researcher.md
      - Web Developer: joining-the-team/web-developer.md
      - Other Volunteer: joining-the-team/other-volunteer.md
  - Docs:
      #- Product Manager:
      #  - Placeholder: about.md
      #- UI Designer:
      #  - Placeholder: about.md
      #- UX Researcher:
      #  - Placeholder: about.md
      - Web Developer:
          - CONTRIBUTING.md: https://github.com/hackforla/CivicTechJobs/blob/main/CONTRIBUTING.md#welcome-to-the-civictechjobs-contributing-guide
          - Backend Architecture: developer/backend.md
          - Design System Helper: developer/design-system.md
          - DevOps Architecture: developer/devops.md
          - Development Culture: developer/development-culture.md
          - Frontend Architecture: developer/frontend.md
          - GitHub Architecture: developer/github.md
          - Git branch Structure: developer/git-branch-structure.md
          - Installation Instructions: developer/installation.md
          - Quickstart Guide: developer/quickstart-guide.md
          - MkDocs Architecture: developer/mkdocs-architecture.md
          - MkDocs - Documentation Guide: developer/mkdocs-guide.md
          - MkDocs - How to Edit: developer/mkdocs-edit-instructions.md
      - Misc:
          - ADA Guide: misc/ada-guide.md
          - Glossary: misc/glossary.md
          - History: misc/history.md
          - Our Process: misc/our-process.md
          - Research Wiki Template: misc/research-wiki-template.md
          - Security Updates: misc/security-updates.md
          - The Team: misc/the-team.md
  - Resources: resources.md
  - CivicTechJobs Repo: https://github.com/hackforla/CivicTechJobs
markdown_extensions:
#  - mkdocs-config
repo_url: https://github.com/hackforla/CivicTechJobs/tree/main/mkdocs
repo_name: GitHub
theme:
  name: material
