site_name: CivicTechJobs Docs
site_url: https://hackforla.github.io/CivicTechJobs/

# Optionals
edit_uri: ""
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
nav:
  - Roles:
      #- Product Manager:
      #  - Placeholder: about.md
      #- UI Designer:
      #  - Placeholder: about.md
      #- UX Researcher:
      #  - Placeholder: about.md
      - Web Developer:
          - CONTRIBUTING.md: https://github.com/hackforla/CivicTechJobs/blob/main/CONTRIBUTING.md#welcome-to-the-civictechjobs-contributing-guide
          - Backend Architecture: developer/backend.md
          - Design System Helper: developer/design-system.md
          - DevOps Architecture: developer/devops.md
          - Development Culture: developer/development-culture.md
          - Frontend Architecture: developer/frontend.md
          - GitHub Architecture: developer/github.md
          - Installation Instructions: developer/installation.md
  - Resources: resources.md
  - CivicTechJobs Repo: https://github.com/hackforla/CivicTechJobs
markdown_extensions:
  - mkdocs-config
repo_url: https://github.com/hackforla/CivicTechJobs/tree/main/mkdocs
repo_name: GitHub
theme:
  name: mkdocs
  nav_style: dark
  navigation_depth: 3
  locale: en
